name: teste_guia_de_moteis
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0-307.0.dev

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  mocktail_image_network: ^1.2.0

flutter:

  uses-material-design: true
